apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demogitops
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: BACKEND_URL
              value: http://backend:8080
